name: GitHub Actions Push Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
env:
  REDOCLY_API_KEY: sk_rXdIPcgjv6U7XIy5h3878WoO3Dg=_lATEPUmDMji/6B+odlKInphandp53yiUVb9V415MoyM=
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Redocly CLI
        run: npm install -g @redocly/cli

      - name: run redocly cli push
        run: |
          REDOCLY_AUTHORIZATION=$REDOCLY_API_KEY npx @redocly/cli@latest push test.yml --destination="CI-CD-test@v3" --organization="testing_redocly"
